GetButtonState_(GameMemory.GameButtons + Button_Up, 2, VK_UP, 0x57);
GetButtonState_(GameMemory.GameButtons + Button_Down, 2, VK_DOWN, 0x53);
GetButtonState_(GameMemory.GameButtons + Button_Left, 2, VK_LEFT, 0x41);
GetButtonState_(GameMemory.GameButtons + Button_Right, 2, VK_RIGHT, 0x44);
GetButtonState_(GameMemory.GameButtons + Button_Space, 1, VK_SPACE);
GetButtonState_(GameMemory.GameButtons + Button_Escape, 1, VK_ESCAPE);
GetButtonState_(GameMemory.GameButtons + Button_Enter, 1, VK_RETURN);
GetButtonState_(GameMemory.GameButtons + Button_Shift, 1, VK_SHIFT);
GetButtonState_(GameMemory.GameButtons + Button_LeftMouse, 1, VK_LBUTTON);
GetButtonState_(GameMemory.GameButtons + Button_RightMouse, 1, VK_RBUTTON);
